### ISSUE TITLE
Error in Chapter05

### ISSUE THREAD

**Issue by yehuihe** [PacktPublishing/Clean-Code-in-Python#5]
There is an error in Chapter05/decorator_wraps_2.py

line 16

return function(**kwargs, **kwargs)

should been

return function(*args, **kwargs)

**Comment by rmariano** [comment]
The line you mention contains something else: https://github.com/PacktPublishing/Clean-Code-in-Python/blob/3c4b4a2fde2ccf28d2e0ec5002b2e1921704164e/Chapter05/decorator_wraps_2.py#L16

And the return value is already as the one you mention: https://github.com/PacktPublishing/Clean-Code-in-Python/blob/3c4b4a2fde2ccf28d2e0ec5002b2e1921704164e/Chapter05/decorator_wraps_2.py#L17

The same considerations apply in the original repository: https://github.com/rmariano/Clean-code-in-Python/blob/main/book/src/ch05/src/decorator_wraps_2.py#L16

Could you double check?

**Comment by yehuihe** [comment]
Hi Mr. Anaya,

I checked the code. Clearly I made a mistake. I think I somehow did see wrong code when I raised the issue. But never mind. Sorry for the trouble.

**Comment by yehuihe** [comment]
Hi Mr. Anaya,

I checked the code. Clearly I made a mistake. I think I somehow did see wrong code when I raised the issue. But never mind. Sorry for the trouble.

________________________________
